### PR TITLE
Don't assume all jobs are available locally

### PR DESCRIPTION
**Pull request by tdtran**
This assumes all the currently running jobs are defined locally, which may not be the case in an environment where the resque instance is shared: https://github.com/tdtran/resque-uniq/blob/master/lib/resque/plugins/unique_job.rb#L31

### CODE REVIEW

**Comment by tdtran** [comment]
Resque itself assumes job classes are defined locally. If resque is shared, the job classes must be shared too.

**Comment by tdtran** [comment]
The attached patch should get the job done. `stale_lock?` would incorrectly return `true` for undefined job class but it's called only during enqueue attempt for the job being enqueued where the job class must certainly be defined.

**Comment by dougcole** [comment]
Wouldn't it be better to return false if we didn't know about the class?

**Comment by tdtran** [comment]
we loop over all jobs in running state and check if their run locks match our run lock. The running jobs are those which cause undefined class error. If so we need to ignore it and move on to the next.

**Comment by dougcole** [comment]
Maybe I'm confused, but returning true for unknown classes means we'll be deleting the locks for all of those right? That seems incorrect.

**Comment by tdtran** [comment]
the key point is `stale_lock?` is only called from `before_enqueue_lock` hook. We pass in as an argument a lock name for a defined job class and check if its lock is stale and if so delete it. Only the lock for the job being queued is checked for staleness and purged if it's stale, not the others.

(We could make `stale_lock?` private method but it seems ruby folks don't like `private` keyword)

**Pull request merged**
